---
title: Teaching, Conference & Useful Ressources
---

## Teaching

### 2022

- Travaux Dirigés Econométrie - Licence 3 Economie & Gestion - *Université Catholique d’Afrique de l’Ouest (UCAO) Abidjan*

### 2023

- Travaux Dirigés Econométrie - Licence 3 Economie & Gestion - Université Catholique d’Afrique de l’Ouest (UCAO) Abidjan 

## Infographics for research paper

1. [**Stata Code**](https://worldbank.github.io/stata-visual-library/)  
2. [**R Code**](https://worldbank.github.io/r-econ-visual-library/)  
3. [**An Economist’s Guide to Visualizing Data**](https://gouvci-my.sharepoint.com/:b:/g/personal/j_migone_stat_plan_gouv_ci/EaRbnR7TnC5PuEZwnGvOtAgB6QXQmq6qmWWLa4oVB7dR1g?e=QFUw3M) 

## Conferences and Research Seminars

1. 3rd International Association of Official Statistics (IAOS) - 17th International Statistic Institute (ISI) Conference in Zambia Livingstone - April 2023
2. 4th International Association of Official Statistics (IAOS) - 19th International Statistic Institute (ISI) Conference in Mexico - May 2024 *failed to present due to VISA*

## Other

1.  [**Causal Inference Book : Causality for Brave and True**](https://matheusfacure.github.io/python-causality-handbook/landing-page.html)  
2. **Econimate** : I love [**youtube.com/econimate**](https://t.co/5O0ziYSjJy) for the way to explain economics research
3. [**Pulic speaking for academic economists from Rachael Meager**](https://gouvci-my.sharepoint.com/:b:/g/personal/j_migone_stat_plan_gouv_ci/EbLOkKzRI5tNs2JG9tTGwFoBXj5IbXdcpepUSA_MRmcjjg?e=8mnZ5F)  
4. [**Micro-simuler l’impact des politiques publiques sur les ménages : pourquoi, comment et lesquelles**](https://gouvci-my.sharepoint.com/:b:/g/personal/j_migone_stat_plan_gouv_ci/EbLOkKzRI5tNs2JG9tTGwFoBXj5IbXdcpepUSA_MRmcjjg?e=YH6Qcw)